language: java

jdk:
  - oraclejdk8

os:
  - linux

install:
  - mvn verify cobertura:cobertura

after_success:
  - "mkdir AutoUpdateLauncherBin"
  - "find -name *.jar -exec cp {} ./AutoUpdateLauncherBin/ \\;"
  - "tar --gzip -cf AutoUpdateLauncher.tar.gz AutoUpdateLauncherBin"
  - "curl --ftp-create-dirs -T AutoUpdateLauncher.tar.gz -u $FTP_USER:$FTP_PASS ftp://$FTP_SERVER/AutoUpdateLauncher/"
  - "bash <(curl -s https://codecov.io/bash)"
  
notifications:
  email:
    recipients:
      - pawelprzytarski@hotmail.com
    on_success: never
    on_failure: always